
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author burakmike
 */
public class jblWords extends javax.swing.JFrame {
    DefaultTableModel model;
    private int id ;
    public jblWords() {
        initComponents();
        updateTable();
    }
    public void updateTable(){
    FileOperations fileOperations = new FileOperations();
        try {
            fileOperations.createFile();
        } catch (IOException ex) {
            Logger.getLogger(jblWords.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        model = (DefaultTableModel)tblWordList.getModel();
        
        ArrayList<Word> wordList = fileOperations.getFile();
        model.setRowCount(0);
        for(Word word : wordList){
        Object[] j = {word.getId(),word.getEng(),word.getTr()};
        model.addRow(j);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblENG1 = new javax.swing.JLabel();
        lblGetWordEng = new javax.swing.JLabel();
        lblTR1 = new javax.swing.JLabel();
        txtSetWordTr = new javax.swing.JTextField();
        btnGetRandomEng = new javax.swing.JButton();
        btnCheckEngToTr = new javax.swing.JButton();
        btnGetAnswer = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblENG2 = new javax.swing.JLabel();
        lblGetWordTR = new javax.swing.JLabel();
        lblTR2 = new javax.swing.JLabel();
        txtSetWordEng = new javax.swing.JTextField();
        btnGetRandomTr = new javax.swing.JButton();
        btnCheckTrToEng = new javax.swing.JButton();
        btnGetAnswerTr = new javax.swing.JButton();
        lblResult1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWordList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddWordEng = new javax.swing.JTextField();
        txtAddWordTr = new javax.swing.JTextField();
        btnAddWord = new javax.swing.JButton();
        lblİsNew = new javax.swing.JLabel();
        btnUpdateWord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblENG1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblENG1.setText("Eng:");

        lblGetWordEng.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        lblTR1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTR1.setText("TR");

        txtSetWordTr.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSetWordTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetWordTrActionPerformed(evt);
            }
        });

        btnGetRandomEng.setText("Get Random Word");
        btnGetRandomEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRandomEngActionPerformed(evt);
            }
        });

        btnCheckEngToTr.setText("Check ");
        btnCheckEngToTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckEngToTrActionPerformed(evt);
            }
        });

        btnGetAnswer.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnGetAnswer.setText("?");
        btnGetAnswer.setLocation(new java.awt.Point(-32468, -32667));
        btnGetAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAnswerActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblENG1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGetWordEng, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSetWordTr)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGetRandomEng)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCheckEngToTr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGetAnswer)))
                .addGap(64, 64, 64)
                .addComponent(lblResult)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblENG1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGetWordEng, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGetRandomEng)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSetWordTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCheckEngToTr)
                                .addComponent(btnGetAnswer))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ENG to TR", jPanel1);

        lblENG2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblENG2.setText("Eng:");

        lblGetWordTR.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        lblTR2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTR2.setText("TR");

        txtSetWordEng.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSetWordEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetWordEngActionPerformed(evt);
            }
        });

        btnGetRandomTr.setText("Get Random Word");
        btnGetRandomTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRandomTrActionPerformed(evt);
            }
        });

        btnCheckTrToEng.setText("Check ");
        btnCheckTrToEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckTrToEngActionPerformed(evt);
            }
        });

        btnGetAnswerTr.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnGetAnswerTr.setText("?");
        btnGetAnswerTr.setLocation(new java.awt.Point(-32468, -32667));
        btnGetAnswerTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAnswerTrActionPerformed(evt);
            }
        });

        lblResult1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblENG2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGetWordTR, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTR2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSetWordEng, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGetRandomTr)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCheckTrToEng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGetAnswerTr)))
                .addGap(64, 64, 64)
                .addComponent(lblResult1)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblENG2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGetWordTR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGetRandomTr)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSetWordEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCheckTrToEng)
                                .addComponent(btnGetAnswerTr))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TR to ENG", jPanel2);

        tblWordList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ENG", "TR"
            }
        ));
        tblWordList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWordListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblWordList);

        jLabel1.setText("Add Word");

        jLabel2.setText("Eng : ");

        jLabel3.setText("Tr : ");

        btnAddWord.setText("Add");
        btnAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordActionPerformed(evt);
            }
        });

        lblİsNew.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        btnUpdateWord.setText("update");
        btnUpdateWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddWordEng)
                                    .addComponent(txtAddWordTr)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAddWord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateWord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblİsNew, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddWordEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddWordTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddWord)
                    .addComponent(lblİsNew)
                    .addComponent(btnUpdateWord))
                .addGap(0, 241, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Word List", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckEngToTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckEngToTrActionPerformed
        FileOperations fileOperations = new FileOperations();
        ArrayList<Word> words ;
        words = fileOperations.getFile();
        String currentWord = words.get(id).getTr().toLowerCase();

        String typedWord = txtSetWordTr.getText().toLowerCase();

        if(currentWord.equals(typedWord)){
            lblResult.setText("TRUE");
        }else{
             lblResult.setText("FALSE");
        }
    }//GEN-LAST:event_btnCheckEngToTrActionPerformed

    private void txtSetWordTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetWordTrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetWordTrActionPerformed

    private void btnGetRandomEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRandomEngActionPerformed
       FileOperations fileOperations = new FileOperations();
       ArrayList<Word> words ;
       words = fileOperations.getFile();
       int size = words.size();
       Random random = new Random();
       id = random.nextInt(size);
       lblGetWordEng.setText(words.get(id).getEng());
    }//GEN-LAST:event_btnGetRandomEngActionPerformed

    private void btnGetAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAnswerActionPerformed
       FileOperations fileOperations = new FileOperations();
       ArrayList<Word> words ;
       words = fileOperations.getFile();
       String translatedWord = words.get(id).getTr().toLowerCase();
       lblResult.setText(translatedWord);
    }//GEN-LAST:event_btnGetAnswerActionPerformed

    private void txtSetWordEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetWordEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetWordEngActionPerformed

    private void btnGetRandomTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRandomTrActionPerformed
       FileOperations fileOperations = new FileOperations();
       ArrayList<Word> words ;
       words = fileOperations.getFile();
       int size = words.size();
       Random random = new Random();
       id = random.nextInt(size);
       lblGetWordTR.setText(words.get(id).getTr());
    }//GEN-LAST:event_btnGetRandomTrActionPerformed

    private void btnCheckTrToEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckTrToEngActionPerformed
        FileOperations fileOperations = new FileOperations();
        ArrayList<Word> words ;
        words = fileOperations.getFile();
        String currentWord = words.get(id).getEng().toLowerCase();
   
        String typedWord = txtSetWordEng.getText().toLowerCase();

        if(currentWord.equals(typedWord)){
            lblResult1.setText("TRUE");
        }else{
             lblResult1.setText("FALSE");
        }
    }//GEN-LAST:event_btnCheckTrToEngActionPerformed

    private void btnGetAnswerTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAnswerTrActionPerformed
       FileOperations fileOperations = new FileOperations();
       ArrayList<Word> words ;
       words = fileOperations.getFile();
       String translatedWord = words.get(id).getEng().toLowerCase();
       lblResult1.setText(translatedWord);
    }//GEN-LAST:event_btnGetAnswerTrActionPerformed

    private void btnAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordActionPerformed
        FileOperations fileOperations = new FileOperations();
       
        ArrayList<Word> words; 
        words = fileOperations.getFile();
        boolean isNew = true;
        for(Word word : words){
            if(word.getEng().equals(txtAddWordEng.getText()) || (word.getEng()+" ").equals(txtAddWordEng.getText()) || (word.getEng()+"  ").equals(txtAddWordEng.getText())){
            isNew= false;
            break;
            }
        
        }
      
        try {
          
            BufferedWriter bWriter = new BufferedWriter(new FileWriter("words.txt"));
           // System.out.println(words.size());
           for(int i = 0 ; i<words.size()+1; i++){
               if(i!=words.size()){
                    bWriter.write((i+1)+"/"+words.get(i).getEng()+"/"+words.get(i).getTr()+"\n");
                   // System.out.println(i+" Yazıldı");
               }else if(!txtAddWordEng.getText().isEmpty() && !txtAddWordTr.getText().isEmpty() && isNew) {
                   bWriter.write((i+1)+"/"+txtAddWordEng.getText()+"/"+txtAddWordTr.getText());
                   txtAddWordEng.setText("");
                   txtAddWordTr.setText("");
                   lblİsNew.setText("Word added to list");
               }else if(!isNew){
                   lblİsNew.setText("Already have!");
                   txtAddWordEng.setText("");
                   txtAddWordTr.setText("");
               }  else break;
           }
            
            bWriter.close();
            updateTable();
            
        } catch (IOException ex) {
            Logger.getLogger(jblWords.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnAddWordActionPerformed

    private void btnUpdateWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateWordActionPerformed
       String engWord= txtAddWordEng.getText();
       String trWord = txtAddWordTr.getText();
       model = (DefaultTableModel) tblWordList.getModel();
       int keyPressed = tblWordList.getSelectedRow();
       FileOperations fileOpr = new FileOperations();
       ArrayList<Word> words = fileOpr.getFile();
       System.out.println(keyPressed);
       boolean isNew = true;
        for(Word word : words){
            if((word.getEng().equals(txtAddWordEng.getText()) || (word.getEng()+" ").equals(txtAddWordEng.getText()) || (word.getEng()+"  ").equals(txtAddWordEng.getText())) &&  word.getTr().equals(txtAddWordTr.getText()) || (word.getTr()+" ").equals(txtAddWordTr.getText()) || (word.getTr()+"  ").equals(txtAddWordTr.getText())){
            isNew= false;
            break;
            }
        
        }
       try {
            BufferedWriter bWriter = new BufferedWriter(new FileWriter("words.txt"));
            for(int i = 0; i < words.size(); i++){
                
                if(i != keyPressed){
                    bWriter.write(words.get(i).getId()+"/"+words.get(i).getEng()+"/"+words.get(i).getTr()+"\n");
                }
                
                else if((i)==keyPressed && isNew && !txtAddWordEng.getText().isBlank() && !txtAddWordTr.getText().isBlank()){
                bWriter.write((keyPressed+1)+ "/"+txtAddWordEng.getText()+"/"+txtAddWordTr.getText()+"\n");
                txtAddWordEng.setText("");
                txtAddWordTr.setText("");
                    lblİsNew.setText("Word Update");
                }else if(!isNew && (i)==keyPressed){
                    bWriter.write(words.get(i).getId()+"/"+words.get(i).getEng()+"/"+words.get(i).getTr()+"\n");
                    lblİsNew.setText("Already Have!");
                }
            }   
          bWriter.close();
          updateTable();
                
                
        } catch (IOException ex) {
            Logger.getLogger(jblWords.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUpdateWordActionPerformed

    private void tblWordListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWordListMouseClicked
        model = (DefaultTableModel) tblWordList.getModel();
        int keyPressed = tblWordList.getSelectedRow();
        txtAddWordEng.setText(model.getValueAt(keyPressed,1).toString());
        txtAddWordTr.setText(model.getValueAt(keyPressed,2).toString());
        
    }//GEN-LAST:event_tblWordListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jblWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jblWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jblWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jblWords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jblWords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWord;
    private javax.swing.JButton btnCheckEngToTr;
    private javax.swing.JButton btnCheckTrToEng;
    private javax.swing.JButton btnGetAnswer;
    private javax.swing.JButton btnGetAnswerTr;
    private javax.swing.JButton btnGetRandomEng;
    private javax.swing.JButton btnGetRandomTr;
    private javax.swing.JButton btnUpdateWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblENG1;
    private javax.swing.JLabel lblENG2;
    private javax.swing.JLabel lblGetWordEng;
    private javax.swing.JLabel lblGetWordTR;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResult1;
    private javax.swing.JLabel lblTR1;
    private javax.swing.JLabel lblTR2;
    private javax.swing.JLabel lblİsNew;
    private javax.swing.JTable tblWordList;
    private javax.swing.JTextField txtAddWordEng;
    private javax.swing.JTextField txtAddWordTr;
    private javax.swing.JTextField txtSetWordEng;
    private javax.swing.JTextField txtSetWordTr;
    // End of variables declaration//GEN-END:variables
}
